services:
  redis:
    image: redis:7.4-alpine
    ports: ["6379:6379"]
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  # ingest-bgp:
  #   build: ./services/ingest-bgp
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #     - STREAM=bgp.events
  #     - STREAM_MAXLEN=50000
  #   depends_on: [redis]

  # gateway:
  #   build: ./services/gateway
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #     - WS_BATCH_MS=1000
  #     - CORS_ORIGIN=http://localhost:3000
  #   ports: ["8000:8000"]
  #   depends_on: [redis]

volumes:
  redisdata:
